# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_notes', '0006_auto_20170605_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='Data de coleta')),
                ('admission_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255, verbose_name='Método de coleta')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal?')),
            ],
        ),
        migrations.AddField(
            model_name='collectedsample',
            name='collection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collected_sample.CollectionMethod', verbose_name='Método de coleta'),
        ),
    ]
