# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collected_sample', '0003_auto_20170611_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectedsample',
            old_name='collection_type',
            new_name='collection_method',
        ),
    ]
