# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collected_sample', '0004_auto_20170615_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedsample',
            name='collection_date',
            field=models.DateField(null=True, verbose_name='Data de coleta'),
        ),
        migrations.AlterField(
            model_name='collectedsample',
            name='collection_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collected_sample.CollectionMethod', verbose_name='Método de coleta'),
        ),
    ]
