# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collected_sample', '0005_auto_20170616_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedsample',
            name='collection_date',
            field=models.DateField(default='1000-01-01', verbose_name='Data de coleta'),
            preserve_default=False,
        ),
    ]
