# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collected_sample', '0006_auto_20170616_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPCR_CDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_type', models.IntegerField(choices=[(1, 'A - Flu A'), (2, 'B - Flu B'), (3, 'Não realizado'), (4, 'Inconclusivo'), (9, 'Ignorado')], default=9, verbose_name='Resultado Tipagem')),
                ('flu_subtype', models.IntegerField(choices=[(1, 'H1'), (2, 'H3'), (3, 'Yamagata'), (4, 'Victoria'), (5, 'Não realizado'), (6, 'Não subtipável'), (9, 'Ignorado')], default=9, verbose_name='Subtipo ou Linhagem')),
                ('details', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='collectedsample',
            name='details',
            field=models.CharField(blank=True, max_length=500, verbose_name='Informações adicionais'),
        ),
        migrations.AddField(
            model_name='rtpcr_cdc',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collected_sample.CollectedSample'),
        ),
    ]
