# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collected_sample', '0006_auto_20170616_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Placeholder RSV')),
                ('performed_inhouse', models.BooleanField(default=True, verbose_name='Realizado na FIOCRUZ/LVRS?')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collected_sample.CollectedSample')),
            ],
        ),
        migrations.CreateModel(
            name='RTPCRExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Placeholder RTPCR')),
                ('performed_inhouse', models.BooleanField(default=True, verbose_name='Realizado na FIOCRUZ/LVRS?')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collected_sample.CollectedSample')),
            ],
        ),
    ]
