"""empty message

Revision ID: dc8ff48db8b7
Revises: 64dd1634e310
Create Date: 2017-11-26 22:57:56.635820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc8ff48db8b7'
down_revision = '64dd1634e310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('order_items', sa.Column('lot_number', sa.String(length=64), nullable=False))
    op.alter_column('stock_products', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('transactions', sa.Column('category', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('stock_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'stocks', ['stock_id'], ['id'])
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'stock_id')
    op.drop_column('transactions', 'product_id')
    op.drop_column('transactions', 'category')
    op.alter_column('stock_products', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('order_items', 'lot_number')
    op.drop_column('order_items', 'expiration_date')
    # ### end Alembic commands ###
