"""empty message

Revision ID: 2d6374da7fca
Revises: 87f04e9eac0c
Create Date: 2017-07-22 15:07:11.508095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6374da7fca'
down_revision = '87f04e9eac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('_ordering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', '_ordering')
    # ### end Alembic commands ###
