"""empty message

Revision ID: 0bab97a3cbf1
Revises: f34963ddd425
Create Date: 2017-07-12 15:14:53.119518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bab97a3cbf1'
down_revision = 'f34963ddd425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clinical_evolutions_admission_id_fkey', 'clinical_evolutions', type_='foreignkey')
    op.create_foreign_key(None, 'clinical_evolutions', 'admissions', ['admission_id'], ['id'])
    op.drop_constraint('hospitalizations_admission_id_fkey', 'hospitalizations', type_='foreignkey')
    op.create_foreign_key(None, 'hospitalizations', 'admissions', ['admission_id'], ['id'])
    op.drop_constraint('uti_hospitalizations_admission_id_fkey', 'uti_hospitalizations', type_='foreignkey')
    op.create_foreign_key(None, 'uti_hospitalizations', 'admissions', ['admission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uti_hospitalizations', type_='foreignkey')
    op.create_foreign_key('uti_hospitalizations_admission_id_fkey', 'uti_hospitalizations', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hospitalizations', type_='foreignkey')
    op.create_foreign_key('hospitalizations_admission_id_fkey', 'hospitalizations', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clinical_evolutions', type_='foreignkey')
    op.create_foreign_key('clinical_evolutions_admission_id_fkey', 'clinical_evolutions', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
