"""empty message

Revision ID: cd73e9067036
Revises: 86429f5125a3
Create Date: 2017-08-09 12:05:39.983768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd73e9067036'
down_revision = '86429f5125a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('invoice_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'invoice_type')
    # ### end Alembic commands ###
