"""empty message

Revision ID: 86429f5125a3
Revises: 14f9bbea8b0a
Create Date: 2017-08-07 18:13:07.617083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86429f5125a3'
down_revision = '14f9bbea8b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'min_stock')
    # ### end Alembic commands ###
