"""empty message

Revision ID: 64dd1634e310
Revises: 9d5061211a4c
Create Date: 2017-11-18 14:59:27.423103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dd1634e310'
down_revision = '9d5061211a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('stock_product', 'stock_products', ['product_id', 'stock_id', 'lot_number'])
    op.drop_constraint('product_lot', 'stock_products', type_='unique')
    op.drop_constraint('stock_products_specification_id_fkey', 'stock_products', type_='foreignkey')
    op.create_foreign_key(None, 'stock_products', 'products', ['product_id'], ['id'])
    op.drop_column('stock_products', 'specification_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('specification_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_products', type_='foreignkey')
    op.create_foreign_key('stock_products_specification_id_fkey', 'stock_products', 'specifications', ['specification_id'], ['id'])
    op.create_unique_constraint('product_lot', 'stock_products', ['specification_id', 'stock_id', 'lot_number'])
    op.drop_constraint('stock_product', 'stock_products', type_='unique')
    op.drop_column('stock_products', 'product_id')
    # ### end Alembic commands ###
