"""empty message

Revision ID: d1e1e4ddf454
Revises: 066ffda5cb98
Create Date: 2017-07-14 16:48:42.882816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e1e4ddf454'
down_revision = '066ffda5cb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('first_symptoms_date', sa.Date(), nullable=True))
    op.add_column('admissions', sa.Column('semepi_symptom', sa.Integer(), nullable=True))
    op.add_column('samples', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('samples', sa.Column('semepi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'semepi')
    op.drop_column('samples', 'admission_date')
    op.drop_column('admissions', 'semepi_symptom')
    op.drop_column('admissions', 'first_symptoms_date')
    # ### end Alembic commands ###
