"""empty message

Revision ID: a8c16ba8ac4a
Revises: b83898f2941c
Create Date: 2017-08-02 13:38:56.195452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c16ba8ac4a'
down_revision = 'b83898f2941c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_subproduct_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'])
    op.drop_column('products', 'subproduct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subproduct', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_subproduct_fkey', 'products', 'products', ['subproduct'], ['id'])
    op.drop_column('products', 'parent_id')
    # ### end Alembic commands ###
