"""empty message

Revision ID: ea583866f61f
Revises: 56a343302149
Create Date: 2017-08-02 10:55:49.850782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea583866f61f'
down_revision = '56a343302149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('details', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'details')
    # ### end Alembic commands ###
