"""empty message

Revision ID: 066ffda5cb98
Revises: 11793d6ece12
Create Date: 2017-07-14 16:03:40.455093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066ffda5cb98'
down_revision = '11793d6ece12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdc_exam', sa.Column('dominant_ct', sa.Integer(), nullable=True))
    op.add_column('cdc_exam', sa.Column('flu_subtype', sa.String(length=16), nullable=True))
    op.add_column('cdc_exam', sa.Column('flu_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdc_exam', 'flu_type')
    op.drop_column('cdc_exam', 'flu_subtype')
    op.drop_column('cdc_exam', 'dominant_ct')
    # ### end Alembic commands ###
