"""empty message

Revision ID: f5234f5f739c
Revises: dc8ff48db8b7
Create Date: 2017-11-29 09:05:35.373701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5234f5f739c'
down_revision = 'dc8ff48db8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('executed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'executed')
    # ### end Alembic commands ###
