"""empty message

Revision ID: 1648dbff9714
Revises: 58b2e44b3691
Create Date: 2017-11-11 12:34:16.917131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1648dbff9714'
down_revision = '58b2e44b3691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('specifications', sa.Column('units', sa.Integer(), nullable=False))
    op.drop_column('specifications', 'stock_unit')
    op.add_column('stock_products', sa.Column('specification_id', sa.Integer(), nullable=False))
    op.add_column('stock_products', sa.Column('stock_id', sa.Integer(), nullable=False))
    op.drop_constraint('product_lot', 'stock_products', type_='unique')
    op.create_unique_constraint('product_lot', 'stock_products', ['specification_id', 'stock_id', 'lot_number'])
    op.drop_constraint('stock_products_product_id_fkey', 'stock_products', type_='foreignkey')
    op.create_foreign_key(None, 'stock_products', 'specifications', ['specification_id'], ['id'])
    op.create_foreign_key(None, 'stock_products', 'stocks', ['stock_id'], ['id'])
    op.drop_column('stock_products', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_products', type_='foreignkey')
    op.drop_constraint(None, 'stock_products', type_='foreignkey')
    op.create_foreign_key('stock_products_product_id_fkey', 'stock_products', 'products', ['product_id'], ['id'])
    op.drop_constraint('product_lot', 'stock_products', type_='unique')
    op.create_unique_constraint('product_lot', 'stock_products', ['product_id', 'lot_number'])
    op.drop_column('stock_products', 'stock_id')
    op.drop_column('stock_products', 'specification_id')
    op.add_column('specifications', sa.Column('stock_unit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('specifications', 'units')
    op.drop_table('stocks')
    # ### end Alembic commands ###
