"""empty message

Revision ID: 14f9bbea8b0a
Revises: c7e28f9a8cc0
Create Date: 2017-08-04 12:58:47.510978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f9bbea8b0a'
down_revision = 'c7e28f9a8cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('allotment', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'allotment', name='stock_product')
    )
    op.add_column('transactions', sa.Column('stock_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'stock_products', ['stock_product_id'], ['id'])
    op.drop_column('transactions', 'allotment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('allotment', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'stock_product_id')
    op.drop_table('stock_products')
    # ### end Alembic commands ###
