"""empty message

Revision ID: 1970d83315ab
Revises: 3e18d834328a
Create Date: 2017-08-11 14:07:37.823615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1970d83315ab'
down_revision = '3e18d834328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_products', 'expiration_date')
    # ### end Alembic commands ###
