"""empty message

Revision ID: bbe9467b5c51
Revises: 1970d83315ab
Create Date: 2017-08-17 18:11:28.335194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe9467b5c51'
down_revision = '1970d83315ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('lot_number', sa.String(length=64), nullable=True))
    op.drop_constraint('stock_product', 'stock_products', type_='unique')
    op.create_unique_constraint('stock_product', 'stock_products', ['product_id', 'lot_number'])
    op.drop_column('stock_products', 'allotment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_products', sa.Column('allotment', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint('stock_product', 'stock_products', type_='unique')
    op.create_unique_constraint('stock_product', 'stock_products', ['product_id', 'allotment'])
    op.drop_column('stock_products', 'lot_number')
    # ### end Alembic commands ###
