"""empty message

Revision ID: df33f3613823
Revises: 15741cc426db
Create Date: 2017-07-14 11:37:46.347709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df33f3613823'
down_revision = '15741cc426db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('age_unit', sa.String(length=1), nullable=True))
    op.add_column('patients', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'birth_date')
    op.drop_column('patients', 'age_unit')
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###
