"""empty message

Revision ID: 8b54b43eb958
Revises: c4f425c04e71
Create Date: 2017-10-16 19:52:12.315090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b54b43eb958'
down_revision = 'c4f425c04e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('catalog_product', 'products', ['manufacturer', 'catalog'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('catalog_product', 'products', type_='unique')
    # ### end Alembic commands ###
