"""empty message

Revision ID: c4f425c04e71
Revises: 9d4580d70b07
Create Date: 2017-08-31 11:39:54.585942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f425c04e71'
down_revision = '9d4580d70b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_products', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('stock_products', 'lot_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_products', 'lot_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('stock_products', 'expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
