"""empty message

Revision ID: b83898f2941c
Revises: ea583866f61f
Create Date: 2017-08-02 13:19:53.751765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83898f2941c'
down_revision = 'ea583866f61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_unit', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('subproduct', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'products', ['subproduct'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'subproduct')
    op.drop_column('products', 'stock_unit')
    # ### end Alembic commands ###
