"""empty message

Revision ID: 3b0d07becb0e
Revises: d700c901ab61
Create Date: 2017-08-09 14:15:57.745882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0d07becb0e'
down_revision = 'd700c901ab61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stock_mail_alert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stock_mail_alert')
    # ### end Alembic commands ###
