"""empty message

Revision ID: f75ac02a2574
Revises: f2ae28a59895
Create Date: 2017-07-09 19:28:30.128771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75ac02a2574'
down_revision = 'f2ae28a59895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdc_exam', sa.Column('details', sa.String(length=255), nullable=True))
    op.add_column('cdc_exam', sa.Column('sample_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cdc_exam', 'samples', ['sample_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cdc_exam', type_='foreignkey')
    op.drop_column('cdc_exam', 'sample_id')
    op.drop_column('cdc_exam', 'details')
    # ### end Alembic commands ###
