"""empty message

Revision ID: d700c901ab61
Revises: cd73e9067036
Create Date: 2017-08-09 12:43:27.722148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd700c901ab61'
down_revision = 'cd73e9067036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('financier', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'financier')
    # ### end Alembic commands ###
