"""empty message

Revision ID: bbc0941c7bc3
Revises: 
Create Date: 2017-07-12 13:14:32.053877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc0941c7bc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccines', sa.Column('last_dose_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccines', 'last_dose_date')
    # ### end Alembic commands ###
