"""empty message

Revision ID: 9a2440ddd946
Revises: 230e86b70e59
Create Date: 2018-05-17 22:34:43.595234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2440ddd946'
down_revision = '230e86b70e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'invoice_value',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'invoice_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
