"""empty message

Revision ID: 129d36205ad9
Revises: a7f9c39dec5b
Create Date: 2018-05-31 16:10:26.252512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129d36205ad9'
down_revision = 'a7f9c39dec5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('admissions', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('cdc_exam', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('cdc_exam', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('samples', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('samples', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'updated_on')
    op.drop_column('samples', 'created_on')
    op.drop_column('patients', 'updated_on')
    op.drop_column('patients', 'created_on')
    op.drop_column('cdc_exam', 'updated_on')
    op.drop_column('cdc_exam', 'created_on')
    op.drop_column('admissions', 'updated_on')
    op.drop_column('admissions', 'created_on')
    # ### end Alembic commands ###
