"""empty message

Revision ID: 53ac0b4e8891
Revises: 38e1524b070f
Create Date: 2018-08-22 14:32:45.483169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53ac0b4e8891'
down_revision = '38e1524b070f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influenza_exam',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('flu_type', sa.String(length=255), nullable=True),
    sa.Column('dominant_ct', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orv_exam',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('orv_type', sa.String(length=255), nullable=True),
    sa.Column('dominant_ct', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cdc_exam')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdc_exam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flu_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dominant_ct', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name='cdc_exam_sample_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cdc_exam_pkey')
    )
    op.drop_table('orv_exam')
    op.drop_table('influenza_exam')
    # ### end Alembic commands ###
