"""empty message

Revision ID: b0c3d09f90a3
Revises: 48058f68c777
Create Date: 2018-05-08 11:46:28.509049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c3d09f90a3'
down_revision = '48058f68c777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('secondary_symptoms', sa.String(length=512), nullable=True))
    op.drop_column('symptoms', 'primary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptoms', sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('admissions', 'secondary_symptoms')
    # ### end Alembic commands ###
