"""empty message

Revision ID: 48058f68c777
Revises: e9a85ac88ef9
Create Date: 2018-04-07 14:00:51.189525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48058f68c777'
down_revision = 'e9a85ac88ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_factors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('primary', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('observed_risk_factors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('risk_factor_id', sa.Integer(), nullable=True),
                    sa.Column('admission_id', sa.Integer(), nullable=True),
                    sa.Column('observed', sa.Boolean(), nullable=True),
                    sa.Column('details', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['admission_id'], ['admissions.id'], ),
                    sa.ForeignKeyConstraint(['risk_factor_id'], [
                                            'risk_factors.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observed_risk_factors')
    op.drop_table('risk_factors')
    # ### end Alembic commands ###
