"""empty message

Revision ID: bc16fb9c58a1
Revises: 230e86b70e59
Create Date: 2018-05-17 23:33:28.337613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc16fb9c58a1'
down_revision = '230e86b70e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice_value', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invoice_value')
    # ### end Alembic commands ###
