"""empty message

Revision ID: 54b4204d4560
Revises: bd8b129ed7dd
Create Date: 2018-04-06 08:47:09.926824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b4204d4560'
down_revision = 'bd8b129ed7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccines', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('vaccines', sa.Column(
        'occurred', sa.Boolean(), nullable=True))
    op.drop_column('vaccines', 'last_dose_date')
    op.drop_column('vaccines', 'applied')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccines', sa.Column(
        'applied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('vaccines', sa.Column('last_dose_date',
                                        sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('vaccines', 'occurred')
    op.drop_column('vaccines', 'date')
    # ### end Alembic commands ###
