"""empty message

Revision ID: edcd04e04e82
Revises: 230e86b70e59
Create Date: 2018-05-17 21:37:41.153009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcd04e04e82'
down_revision = '230e86b70e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invoice_value')
    # ### end Alembic commands ###
