"""empty message

Revision ID: 230e86b70e59
Revises: 032d311ba5f9
Create Date: 2018-05-17 15:29:57.980559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230e86b70e59'
down_revision = '032d311ba5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_ray',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage', sa.String(length=255), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x_ray')
    # ### end Alembic commands ###
