"""empty message

Revision ID: d920c0544fc4
Revises: 57a522c232f7
Create Date: 2018-05-20 13:29:53.808593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd920c0544fc4'
down_revision = '57a522c232f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'expiration_date')
    # ### end Alembic commands ###
