"""empty message

Revision ID: 38e1524b070f
Revises: f15753a58058
Create Date: 2018-08-22 14:02:54.984418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e1524b070f'
down_revision = 'f15753a58058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'zone')
    op.drop_column('addresses', 'details')
    op.alter_column('cdc_exam', 'flu_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('cdc_exam', 'flu_subtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdc_exam', sa.Column('flu_subtype', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.alter_column('cdc_exam', 'flu_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.add_column('addresses', sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
