"""empty message

Revision ID: 8f67d4643adb
Revises: 3d2fba07fd93
Create Date: 2018-05-16 15:33:28.479644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f67d4643adb'
down_revision = '3d2fba07fd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antiviral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('antiviral')
    # ### end Alembic commands ###
