"""empty message

Revision ID: 1b0ec833b6f7
Revises: 129d36205ad9
Create Date: 2018-06-02 13:46:29.685295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0ec833b6f7'
down_revision = '129d36205ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('lot_number', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('patched_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'order_items', ['order_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'patched_transaction_id')
    op.drop_column('transactions', 'order_item_id')
    op.drop_column('transactions', 'lot_number')
    op.drop_column('transactions', 'expiration_date')
    # ### end Alembic commands ###
