"""empty message

Revision ID: a7f9c39dec5b
Revises: 18e4f860a8ab
Create Date: 2018-05-21 23:17:38.911472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f9c39dec5b'
down_revision = '18e4f860a8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cdc_exam', 'dominant_ct',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_column('methods', 'primary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methods', sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('cdc_exam', 'dominant_ct',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
