"""empty message

Revision ID: e9b7f5b6ec33
Revises: bc16fb9c58a1
Create Date: 2018-05-20 12:05:06.626848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b7f5b6ec33'
down_revision = 'bc16fb9c58a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('lot_number', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key('transactions_order_item_id_fkey', 'transactions', 'order_items', ['order_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_order_item_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'order_item_id')
    op.drop_column('transactions', 'lot_number')
    # ### end Alembic commands ###
