"""empty message

Revision ID: f15753a58058
Revises: 9648c552f308
Create Date: 2018-06-13 23:44:34.272653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15753a58058'
down_revision = '9648c552f308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('request_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admissions', 'request_number')
    # ### end Alembic commands ###
