"""sample_fk

Revision ID: f2ae28a59895
Revises: 3131912cdbcb
Create Date: 2017-07-09 16:49:14.857031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ae28a59895'
down_revision = '3131912cdbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('admission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'samples', 'admissions', ['admission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'admission_id')
    # ### end Alembic commands ###
