# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labsys.custom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission_notes', '0006_auto_20170605_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed', labsys.custom.models.YesNoIgnoredField(default=None, verbose_name='Apresenta o sintoma?')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Informações adicionais')),
                ('admission_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do sintoma')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Sintoma principal?')),
            ],
        ),
        migrations.AddField(
            model_name='observedsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.Symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='observedsymptom',
            unique_together=set([('symptom', 'admission_note')]),
        ),
    ]
