# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_auto_20170611_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedsymptom',
            name='admission_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote', verbose_name='Nota de admissão'),
        ),
        migrations.AlterField(
            model_name='observedsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.Symptom', verbose_name='Sintoma'),
        ),
    ]
