# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gal', models.CharField(max_length=30)),
                ('requestor', models.CharField(max_length=255)),
                ('health_unit', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
