# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionnote',
            old_name='requestor',
            new_name='requester',
        ),
    ]
