# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0002_auto_20170602_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionnote',
            name='admission_date',
            field=models.DateField(blank=True, help_text='quando a amostra chegou no LVRS', null=True, verbose_name='Data de admissão LVRS'),
        ),
    ]
