# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0003_admissionnote_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionnote',
            name='admission_date',
            field=models.DateField(blank=True, help_text='quando a amostra chegou no LVRS', null=True, verbose_name='Data de entrada (LVRS)'),
        ),
        migrations.AlterField(
            model_name='admissionnote',
            name='health_unit',
            field=models.CharField(help_text='unidade onde o paciente foi avaliado', max_length=255, verbose_name='Unidade de saúde'),
        ),
        migrations.AlterField(
            model_name='admissionnote',
            name='id_gal',
            field=models.CharField(max_length=30, verbose_name='Número da requisição (GAL interno)'),
        ),
        migrations.AlterField(
            model_name='admissionnote',
            name='requester',
            field=models.CharField(help_text='LACEN ou instituto que solicitou o exame', max_length=255, verbose_name='Instituto solicitante'),
        ),
    ]
