# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0005_admissionnote_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionnote',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Patient'),
        ),
    ]
