# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0008_auto_20170612_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionnote',
            name='id_gal',
        ),
        migrations.AddField(
            model_name='admissionnote',
            name='id_lvrs_intern',
            field=models.CharField(default='', help_text='Número interno do laboratório, ex: 334/2017', max_length=30, verbose_name='Número interno (LVRS)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionnote',
            name='id_request_gal',
            field=models.CharField(default='', max_length=30, verbose_name='Número da requisição (GAL)'),
            preserve_default=False,
        ),
    ]
