# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labsys.custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0009_auto_20170612_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', labsys.custom.models.YesNoIgnoredField(verbose_name='Ocorreu?')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data de ocorrência')),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
