# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import labsys.custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0010_fluvaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', labsys.custom.models.YesNoIgnoredField()),
                ('date', models.DateField(blank=True, null=True)),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', labsys.custom.models.YesNoIgnoredField()),
                ('date', models.DateField(blank=True, null=True)),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTIHospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', labsys.custom.models.YesNoIgnoredField()),
                ('date', models.DateField(blank=True, null=True)),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fluvaccine',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluvaccine',
            name='occurred',
            field=labsys.custom.models.YesNoIgnoredField(),
        ),
    ]
