# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0013_auto_20170622_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiviral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Antiviral utilizado')),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AntiviralUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', models.NullBooleanField(default=None, verbose_name='Uso de Antiviral?')),
                ('date', models.DateField(blank=True, help_text='Data do início do tratamento com antiviral', null=True, verbose_name='Data de uso')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Informações adicionais')),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
                ('antiviral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_notes.Antiviral', verbose_name='Antiviral utilizado')),
            ],
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tipo de Raio X')),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XRayExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred', models.NullBooleanField(default=None, verbose_name='Realizou exame de Raio-X?')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data de realização do exame')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Informações adicionais')),
                ('admission_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission_notes.AdmissionNote')),
                ('xray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_notes.XRay', verbose_name='Tipo de exame realizado')),
            ],
        ),
    ]
