# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0014_antiviral_antiviraluse_xray_xrayexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiviraluse',
            name='antiviral',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_notes.Antiviral', verbose_name='Antiviral utilizado'),
        ),
        migrations.AlterField(
            model_name='xrayexam',
            name='xray',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_notes.XRay', verbose_name='Tipo de exame realizado'),
        ),
    ]
