# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_notes', '0015_auto_20170622_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiviraluse',
            name='occurred',
        ),
        migrations.RemoveField(
            model_name='xrayexam',
            name='occurred',
        ),
        migrations.AlterField(
            model_name='antiviraluse',
            name='antiviral',
            field=models.IntegerField(choices=[(1, '1 - Não usou'), (2, '2 - Oseltamivir'), (3, '3 - Zanamivir'), (4, '4 - Outro, especifique'), (9, '9 - Ignorado')], default=9, help_text='Caso "outro", informar', verbose_name='Selecione'),
        ),
        migrations.AlterField(
            model_name='antiviraluse',
            name='details',
            field=models.CharField(blank=True, help_text='Ex.: outro antiviral', max_length=255, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='xrayexam',
            name='details',
            field=models.CharField(blank=True, help_text='Ex.: outro tipo de Raio-X', max_length=255, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='xrayexam',
            name='xray',
            field=models.IntegerField(choices=[(1, '1 - Normal'), (2, '2 - Infiltrado intersticial'), (3, '3 - Consolidação'), (4, '4 - Misto'), (5, '5 - Outro, especifique'), (6, '6 - Não realizado'), (9, '9 - Ignorado')], default=9, help_text='mais sugestiva para diagnóstico de SRAG', verbose_name='Selecione'),
        ),
        migrations.DeleteModel(
            name='Antiviral',
        ),
        migrations.DeleteModel(
            name='XRay',
        ),
    ]
