# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(choices=[(1, 'Brasil'), (2, 'Outros')], default=1, verbose_name='País')),
                ('state', models.CharField(max_length=2, verbose_name='Estado UF')),
                ('city', models.CharField(max_length=255, verbose_name='Município')),
                ('neighborhood', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('zone', models.IntegerField(choices=[(1, 'Urbana'), (2, 'Rural'), (3, 'Periurbana'), (9, 'Ignorado')], default=9, verbose_name='Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('age_in_hours', models.PositiveIntegerField(verbose_name='Idade')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Ignorado')], default='I', max_length=1, verbose_name='Sexo')),
                ('pregnant', models.IntegerField(choices=[(1, '1° Trimestre'), (2, '2° Trimestre'), (3, '3° Trimestre'), (4, 'Idade gestacional ignorada'), (5, 'Não'), (6, 'Não se aplica'), (9, 'Ignorado')], default=9, verbose_name='Gestante')),
                ('residence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Locality', verbose_name='Endereço de residência')),
            ],
        ),
    ]
