# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado UF'),
        ),
    ]
