# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20170603_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zone',
            field=models.IntegerField(choices=[(1, '1 - Urbana'), (2, '2 - Rural'), (3, '3 - Periurbana'), (9, '9 - Ignorado')], default=9, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pregnant',
            field=models.IntegerField(choices=[(1, '1 - 1° Trimestre'), (2, '2 - 2° Trimestre'), (3, '3 - 3° Trimestre'), (4, '4 - Idade gestacional ignorada'), (5, '5 - Não'), (6, '6 - Não se aplica'), (9, '9 - Ignorado')], default=9, verbose_name='Gestante'),
        ),
    ]
