# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20170604_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(choices=[(1, 'Brasil'), (2, 'Outros')], default=1, verbose_name='País')),
                ('state', models.CharField(max_length=2, verbose_name='Estado UF')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Município')),
                ('neighborhood', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('zone', models.IntegerField(choices=[(1, '1 - Urbana'), (2, '2 - Rural'), (3, '3 - Periurbana'), (9, '9 - Ignorado')], default=9, verbose_name='Zona')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patient',
            name='pregnant',
            field=models.IntegerField(choices=[(1, '1° Trimestre'), (2, '2° Trimestre'), (3, '3° Trimestre'), (4, 'Idade gestacional ignorada'), (5, 'Não'), (6, 'Não se aplica'), (9, 'Ignorado')], default=9, verbose_name='Gestante'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Locality', verbose_name='Endereço de residência'),
        ),
    ]
