# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20170604_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'M - Masculino'), ('F', 'F - Feminino'), ('I', 'I - Ignorado')], default='I', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pregnant',
            field=models.IntegerField(choices=[(1, '1 - 1° Trimestre'), (2, '2 - 2° Trimestre'), (3, '3 - 3° Trimestre'), (4, '4 - Idade gestacional ignorada'), (5, '5 - Não'), (6, '6 - Não se aplica'), (9, '7 - Ignorado')], default=9, verbose_name='Gestante'),
        ),
    ]
