# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20170605_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Locality', verbose_name='Endereço de residência'),
        ),
    ]
