# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20170612_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
