# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20170612_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_in_hours',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='age_unit',
            field=models.CharField(choices=[('A', 'A - Anos'), ('M', 'M - Meses'), ('D', 'D - Dias'), ('H', 'H - Horas')], default='A', max_length=1, verbose_name='Tipo Idade'),
        ),
    ]
