# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluvaccine',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='samples.PatientRegister'),
        ),
        migrations.AlterField(
            model_name='fluvaccine',
            name='was_applied',
            field=models.NullBooleanField(verbose_name='Recebeu vacina contra gripe'),
        ),
        migrations.AlterField(
            model_name='patientregister',
            name='id_gal_origin',
            field=models.CharField(max_length=255, verbose_name='ID Gal Origem'),
        ),
    ]
