# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20170424_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='Data de coleta')),
                ('patient_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.PatientRegister')),
            ],
        ),
    ]
