# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20170424_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do sintoma')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Principal?')),
            ],
        ),
    ]
