# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed', models.NullBooleanField(default=None, verbose_name='Apresenta sintoma?')),
                ('patient_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.PatientRegister')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Symptom')),
            ],
        ),
    ]
