# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_observedsymptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='observed_symptoms',
            field=models.ManyToManyField(through='samples.ObservedSymptom', to='samples.Symptom'),
        ),
    ]
