# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20170426_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionnote',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Patient'),
        ),
        migrations.AlterField(
            model_name='fluvaccine',
            name='was_applied',
            field=samples.custom.models.YesNoIgnoredField(verbose_name='Recebeu vacina contra gripe?'),
        ),
    ]
