# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_auto_20170427_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluvaccine',
            name='date_applied',
            field=models.DateField(null=True, verbose_name='Data de aplicação'),
        ),
    ]
