# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_fluvaccine_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedsample',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de coleta'),
        ),
        migrations.AlterField(
            model_name='fluvaccine',
            name='date_applied',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aplicação'),
        ),
    ]
