# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:35
from __future__ import unicode_literals

from django.db import migrations
import samples.custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20170526_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedsymptom',
            name='observed',
            field=samples.custom.models.YesNoIgnoredField(default=None, verbose_name='Apresenta sintoma?'),
        ),
    ]
