# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_auto_20170529_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Symptom', verbose_name='Sintoma principal'),
        ),
    ]
